name: Build and run tests

on:
  # always test main
  push:
  # test PRs
  pull_request:
  # allow triggering tests, ignores skip check
  workflow_dispatch:

jobs:
  build-yosys:
    name: Just build Yosys
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        mkopts:
          - 'ENABLE_LTO=1'
          - ''
      fail-fast: false
    steps:
      - name: Checkout Yosys
        uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/actions/setup-build-env

      - name: Tool versions
        shell: bash
        run: |
          $CC --version

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          make -f ../Makefile config-$CC
          make -f ../Makefile -j$procs ${{ matrix.mkopts }} yosys
